vich_uploader:
  db_driver: orm

  mappings:
    amiibo_images:
      uri_prefix: /images/amiibo
      upload_destination: '%kernel.project_dir%/public/images/amiibo'
      namer: Vich\UploaderBundle\Naming\UniqidNamer